# Production environment override
services:

    tenants_api:
        build:
            target: frankenphp_prod
        environment:
            APP_SECRET: ${APP_SECRET}
            FRANKENPHP_WORKER_CONFIG: worker ./public/index.php