services:

    tenants-api:
        container_name: ${API_CONTAINER_NAME}
        image: ${API_CONTAINER_IMAGE_NAME}
        restart: unless-stopped
        build:
            context: .
            dockerfile: etc/frankenphp/Dockerfile
        volumes:
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - local_network
        healthcheck:
            test: [ "CMD-SHELL", "curl -fsSL https://${API_SERVER_NAME}/healthcheck || exit 1" ]
            interval: 1s
            timeout: 5s
            retries: 3
        ports:
            # HTTP
            - target: 80
              published: 80
              protocol: tcp
            # HTTPS
            - target: 443
              published: 443
              protocol: tcp
            # HTTP/3
            - target: 443
              published: 443
              protocol: udp
        #depends_on:
        #    tenants_postgresql:
        #        condition: service_healthy


    # Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
    ###> symfony/mercure-bundle ###
    ###< symfony/mercure-bundle ###

    ###> doctrine/doctrine-bundle ###
    #tenants_postgresql:
    #    container_name: tenants_postgresql
    #    image: tenants_postgresql
    #    restart: unless-stopped
    #    build:
    #        context: .
    #        dockerfile: etc/postgresql/Dockerfile
    #    environment:
    #        POSTGRES_DB: ${POSTGRES_DB}
    #        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #        POSTGRES_USER: ${POSTGRES_USER}
    #    ports:
    #        - "5432:5432"
    #    healthcheck:
    #        test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
    #        timeout: 5s
    #        retries: 5
    #        start_period: 60s
    #    networks:
    #        - local_network
    #    volumes:
    #        - postgres:/var/lib/postgresql/data:rw
    #        # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
    #        - ./etc/postgresql/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
    caddy_data:
    caddy_config:
    #postgres:

networks:
    local_network:
