doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        Tenants\Shared\Infrastructure\Persistence\Doctrine\Migrations: '%kernel.project_dir%/../../../src/Shared/Infrastructure/Persistence/Doctrine/Migrations'

    enable_profiler: false
